### PR TITLE
Add support for BIM360 models

### PR DESCRIPTION
**Pull request by dimven**
Hello Dan,

As more projects are moving to BIM360Design (or whatever they decide to call it next month), the urge to be able to batch process them becomes ever greater. What Autodesk would like us to do is stick to the forge platform but IMHO that still comes with a couple of big disadvantages:
- The revit engine does not load a UI. That means that any error that would require a user action (which revit has way too many of), would halt the process till it times out.
- It's a bit of a black box - you can't debug it step by step inside the "cloud environment" like you would on a regular "desktop" plugin, and you can't guarantee that the plugin that works on your PCs will behave the same way in the server environment.
- It greatly raises the entry level for new developers: you now need to learn all kinds of web paradigms like three-legged oAuth, RESTful apis, etc.

My goal with the current PR is to at least partially alleviate some of the above:
- We get to reuse all of the amazing work you've put into the RBP over the years
- We can run our scripts and graphs just as before and without any modification and additional testing
- Leave all of the authentication and data management to Autodesk

Since you're the most knowledgeable person with the intricacies of RBP, I really hope we can work on this together to integrate it properly, improve it further and get it as ready as possible for distribution. You can have a look at its current state here:
https://www.youtube.com/watch?v=3IdC_PPFEiE

It's based around a ui automation framework called [TestStack.White](https://github.com/TestStack/White) . I opted for it instead of .NET's built in WPF automation because it can work with both WPF and Win32 objects and integrates a fairly robust methodology for waiting for the host window to become responsive after each UI action . I'm running it on yet another separate process, as to not interfere with the rest of RBP. It was also necessary to rely on revit's idle event because that's the only effective way that I found out of learning when Revit is fully done with loading its interface or opening a bim360 document.

There's a long list of limitations:
- The end user needs to be logged in to the "right" account and have set up all the necessary access permissions in advance.
- You must specify the full path, _including the "Hub" name_, in the file path (ie `BIM 360:\\ADN Bad Monkeys\My Project Name\My Project BIM Files\My_Revit_File.rvt`).
- You must manually specify the revit version to be used, since we can't use stuff like `BasicFileInfo` on the cloud path.
- There's no integration with RvtBatchMonitor and no detailed reporting of what went wrong, when things go wrong. Right now you have to look at the error output of the OpenCloudModel.exe process.
- I haven't looked into supporting Dynamo at this point. 😞 
- The code might not meet your guidelines ?

### CODE REVIEW

**Comment by DanRumery** [comment]
@dimven 
Hi Dimitar

First off I’m impressed by your approach! The code is fine as far as conventions and naming goes. I’ll have to dig deeper to see how it can better integrate with the existing modules. Perhaps the UI interaction logic can be merged somehow into the existing Revit dialog box handler logic so that a separate process isn’t needed for that. I do foresee this approach being a little flaky but I agree it’s better than nothing. It does make me wonder if a hybrid Forge API approach would be more manageable...

BTW unfortunately for me I don’t have access to a BIM360 / Forge account at the moment so I can’t play with this to test the approach. ( I’ve been taking a break from working for a while but I want to get back to making money in the new year =) )

I agree the Forge platform seems a step backwards in term of the Revit API automation / developer experience. Last time I checked (a while ago now) I couldn’t get cloud file access to work in the Revit API. I don’t know if Autodesk has made this possible yet in Revit 2020? It would be far simpler approach if the Revit API could open, sync, etc. cloud models given a cloud path (even if we’d have to use Forge API to obtain access to the platform and the cloud path). Thoughts?

**Comment by dimven** [comment]
Still nothing public in the API to open cloud documents. Revit 2020(.1?) introduced the option to save a model to the cloud and then convert it to a workshared model, but even then you need the guid of the desired cloud folder and you can only get that if you're running on top of Forge...

**Comment by dimven** [comment]
Update: Autodesk broke this approach in 2020 because it removed BIM360 from the open dialog :(

https://knowledge.autodesk.com/support/revit-products/troubleshooting/caas/sfdcarticles/sfdcarticles/BIM-360-icon-does-not-appear-in-Revit-2020-File-Open-dialogue-box.html

https://forums.autodesk.com/t5/revit-architecture-forum/bim-360-icon-doesn-t-show-up-in-revit-2020-open-dialogue-box/td-p/8729260

Looking for alternative approaches. Unfortunately the WPF CefSharp host is inaccessible through traditional automation libraries.

**Comment by DanRumery** [comment]
@dimven That's a real shame but not surprising of Autodesk to do that :)

It does seem as if they're discouraging future automation outside of their forge platform.

**Comment by DanRumery** [comment]
@dimven 

Hi Dimitar

Now that I have access to Forge and BIM360 I'll try and see how easy (or painful) it is to perform the OAuth2 etc required by Forge in order to access the model Guids. There is a trick for doing Oauth2 without a server by hosting a browser directly in the app where it can retrieve the access token in the redirect (I think just using a dummy URL would work, just have to detect and capture it in the hosted browser.)

What do you think? Did you make any progress for a different workaround?

It certainly is annoying to have to provide a web server for an otherwise desktop-based addin just because Oauth2 requires it for the redirect.....

**Comment by dimven** [comment]
Unfortunately, I haven't made any headway.

I agree that the process is too convoluted right now. Maybe there's a way to piggyback on the oauth that's already built into Revit.

**Comment by dimven** [comment]
I've been digging around a bit. I'm pretty sure we can't use the Revit home screen connection. For the alternative - before you can establish a new forge authentication, you must first register a forge app, then the hub admin has to add your app and finally, you'll need to distribute your app's client id and client secret before you can get access to any bim360 data.

I'm thinking the alternative is to let organizations acquire the ProjectGuid and ModelGuid by themselves internally and then modify RBP so that it works with a list of guid pairs as the filepath input. Then we can use the `ModelPathUtils.ConvertCloudGUIDsToCloudPath` to open the file. I tested that and as long as the currently logged in revit user has permissions to the model file, everything works fine. How does that sound to you?

**Comment by DanRumery** [comment]
Using the [.NET Forge API SDK](https://github.com/Autodesk-Forge/forge-api-dotnet-client) I was able to do the three-legged OAuth2 using a HttpListener (similar to the tutorial in that repo). Setting up the listener required running a `net use` command under an admin account. That, in addition to the additional setup you described makes the whole setup process quite laborious I agree.

The guid workaround sounds like a decent compromise. But what's annoying about this is RBP won't be able to assess ahead of time whether the model exists or it's Revit version or "size". So it'd be up to the user to make sure they're explicitly using the correct Revit version and that they are signed in to their account before running the batch process.

I'll give it a go...

**Comment by DanRumery** [comment]
So I guess the "file path" for the cloud models could be:
`[<Revit version>] <Project Guid> <Model Guid>`

With Revit version being optional (resort to RBP Revit version setting if its not specified here)

**Comment by DanRumery** [comment]
@dimven 
Hi Dimitar

Some good news, I've added the capability to open cloud models as per your recommended approach:

That is, the Revit file list allows for specifying the project and model guids instead of a file path:
`[<Revit version>] <Project Guid> <Model Guid>`

Note that these are space-delimited, not tab-delimited, i.e. all two/three values must sit in the first column. The brackets around Revit version means it's optional.

Examples:
`2020 75b6464c-ba0f-4529-b049-0de9e473c2d6 0d54b8cc-3837-4df2-8c8e-0a94f4828868`
`75b6464c-ba0f-4529-b049-0de9e473c2d6 0d54b8cc-3837-4df2-8c8e-0a94f4828868`

I haven't yet deployed a beta release or anything, so if you want to try it out you'll have to pull the latest commits on `master` branch in this repo (the commits are not yet published to the BVN one), and build from source code.

Incidently I've also made a preliminary upgrade to support Revit 2021 (also still in beta testing). So feel free to have a play with RBP and Revit 2021.

Processing options are limited due to the nature of cloud models. E.g. detach/create local are meaningless for cloud models. Also I can't provide much information to the user about the model until the document is opened in memory. It's very much up to the user to know what they're doing and get things right (including the Revit version to target).

Let me know if you have any feedback.

**Comment by dimven** [comment]
That's great! Agreed, without using forge, I can't think of any way of getting any meaningful data out of the cloud model prior to opening it. But I think that will be totally fine. Just getting the guids in the first place is quite the feat, so I expect any potential end users will be aware of what they're doing and will require little hand-holding.

I'm closing this PR, since I don't think it will be of any use going forward. Once again, thanks for all your help on this and on all your work on RBP in general :)

**Comment by DanRumery** [comment]
Thank you :) 

When I make the release I'll still add you in the credits since you put quite some effort into this stuff even if the PR didn't make it into the mainline branch. The PR branch still lives on the official repo and I thought for that reason it would show you as a contributor but it doesn't. So at least I'll add you to the credits.

**Comment by DanRumery** [comment]
On the original repo (BVN) I merged your branch then did a revert, which means that github shows you as a contributor now :)

**Pull request closed without merging**
